### ISSUE TITLE
do we need to import the autogenerated files?

### ISSUE THREAD

**Issue by goneri** [ansible-network/collection_prep#23]
Hi all,

Importing a large number of auto-generated files make me file a bit uncomfortable.  I would prefer to avoid duplicated data in the repository, and this can also confuse the contributors. In addition, we can still face situation where the modules and the .rst will be out-of-sync. Also, if we modify `collection_prep`, we will need to regenerate the .rst of all the collection repositories.

I understand the `README.md` change has to be imported in the repository, but can we generate the .rst files just before we build the release tarballs? This could even be part of the zuul release pipeline.

**Comment by pabelanger** [comment]
I haven't looked how rst files are generated, I am guessing from .py files some how.  But, regardless if they are in repo or not, this process should be automated. Creating a new docs job, to generate, confirm they are not out of sync, then published to review for each PR.

This is something I have wanted to do for a while, just haven't done it yet.

**Comment by goneri** [comment]
You assume we need to keep the .rst files in the repository. Can we just ship them in the release tarballs instead?

**Comment by pabelanger** [comment]
IMO, they can be in repo or not, there is pros / cons for each.  In repo, users of git would be able to see them.

if they are to be in tarballs is another topic, would you not want compiled HTML files, for better viewing?

**Comment by jborean93** [comment]
> You assume we need to keep the .rst files in the repository

Wasn't the whole point of the add_docs script so that people who can't access AH can still view the module docs. Just bundling the docs as rst in the collection still doesn't provide an easy way for people to actually view the data without installing them. We also have `ansible-doc` as the proper mechanism to view docs offline.
