### ISSUE TITLE
What's "rewuires"?

### ISSUE THREAD

**Issue by mariolenz** [ansible-network/collection_prep#62]
https://github.com/ansible-network/collection_prep/blob/d6cb3dca5bf3d29a416c5271893ac4d34dcf6b36/README.md#L43

English isn't my first language, but did you mean "reviewers"? If "rewuires" is correct, please enlighten me and tell me what it means. I don't think I came across this word yet.

**Comment by phospi** [comment]
Please have a look at the docs: [Link](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_structure.html)

It is meant to be `requires_ansible`  

As the docs state:
`The version of Ansible required to use the collection. Multiple versions can be separated with a comma.`

**Comment by mariolenz** [comment]
> It is meant to be `requires_ansible`

Yeah, "meant to be". But it isn't. I've created PR #63 to fix this typo.
