### ISSUE TITLE
collection_prep_add_docs: Allow ignoring static documentation

### ISSUE THREAD

**Issue by mariolenz** [ansible-network/collection_prep#64]
We have some static documentation in `docs/docsite`. It looks like `collection_prep_add_docs -p .` removes _everything_ in `docs`. It would be great if we could tell `collection_prep_add_docs` to ignore / _not_ remove some files or directories.

Please see ansible-collections/community.vmware#1003 for more information.

**Comment by Akasurde** [comment]
Yes, I agree with @mariolenz. We should have some flag which will allow user to skip / not remove the files under `docs`.
